### ISSUE TITLE
handshake operation timeout when trying to get result

### ISSUE THREAD

**Issue by hotmeme** [mtzgroup/chemcloud-server#101]
Here's a traceback:
```
Traceback (most recent call last):
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 154, in _connect
    stream = stream.start_tls(**kwargs)
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 168, in start_tls
    raise exc
  File "/global/software/Anaconda3/2022.05/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: _ssl.c:1112: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kukier/projects/dioxetane/scripts/terachem-rework/cc_submit.py", line 303, in <module>
    main()
  File "/home/kukier/projects/dioxetane/scripts/terachem-rework/cc_submit.py", line 294, in main
    future_results = compute_program_inputs(program_inputs)
  File "/home/kukier/projects/dioxetane/scripts/terachem-rework/cc_submit.py", line 247, in compute_program_inputs
    future_result = client.compute("geometric", inp, collect_files=True)
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/chemcloud/client.py", line 137, in compute
    if self.supported_programs is not None:
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/chemcloud/client.py", line 76, in supported_programs
    self._set_openapi_specification()
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/chemcloud/client.py", line 51, in _set_openapi_specification
    self._openapi_spec = self._client._request(
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/chemcloud/http_client.py", line 194, in _request
    response = client.send(request)
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/global/software/Anaconda3/2022.05/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/kukier/projects/dioxetane/env/lib/python3.9/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:1112: The handshake operation timed out
```

**Comment by coltonbh** [comment]
Fixed with [ChemCloud Client 0.13.0 Release](https://github.com/mtzgroup/chemcloud-client/releases/tag/0.13.0) that added retry logic for request errors.
